name: Attach VSIX

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  package-and-attach:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci

      - name: Compile Extension
        run: npm run compile

      - name: Package VSIX
        run: npx @vscode/vsce package --out copy-code-context.vsix

      - name: Upload VSIX to Release
        uses: softprops/action-gh-release@v1
        with:
          files: copy-code-context.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
